### ISSUE TITLE
S7678G SDK question

### ISSUE THREAD

**Issue by lyusupov** [leotseng1977/s7678s_ping_pong_sdk#2]
Hi Leo!

Is it possible to deploy S76G SDK as well?
Same way as you already did here with S76S variant.

   Best regards,
   Linar.

**Comment by leotseng1977** [comment]
Yeah, you can use it to deploy as what u want.
Since the basic RF function is OK already.

**Comment by lyusupov** [comment]
Leo,
Thank you for the response!

We probably misunderstood each other...
My request was addressed to you, author of the SDK and many of AcSiP's PDF documents -
We all can see that you've deployed SDK for S76S on the GitHub 2 years ago.
Could you, please, deploy SDK for S76G on the GitHub alongside the S76S variant ?
Because of: **your SDK is a great source of information for every S7678x Open Source developer** !
